### PR TITLE
Homu: check the Cirrus status for libc builds.

### PR DESCRIPTION
**Pull request by asomers**
Suggested by @alexcrichton in https://github.com/rust-lang/libc/pull/1167

### CODE REVIEW

**Comment by alexcrichton** [comment]
@asomers it looks like Cirrus CI may not be using the same status API that travis/appveyor are using? The statuses for the most recent PR - https://api.github.com/repos/rust-lang/libc/statuses/de0775936049475fe42f71dd7bc9004ec1309317 - don't include cirrus ci anywhere in there, causing it to time out as homu waits for a status it'll never receive

**Comment by asomers** [comment]
How many different status APIs are there?  Cirrus is definitely reporting something, because you can see it at https://github.com/rust-lang/libc/runs/39476297 .

**Comment by alexcrichton** [comment]
I'm not sure. I agree Cirrus is reporting *something*, but homu may not be able to read it

**Comment by asomers** [comment]
Looks like this is going to require some Homu work.  Cirrus says that they report status exclusively through Github's new check-suite API.  For the commit in question, you can see it with this command: ```curl "https://api.github.com/repos/rust-lang/libc/commits/de0775936049475fe42f71dd7bc9004ec1309317/check-suites" -H "Accept: application/vnd.github.antiope-preview+json"```.  See the linked issue for more details.

**Comment by alexcrichton** [comment]
Ok thanks for the info, mind posting a PR to revert this? We'll have to hand-verify FreeBSD for now.

**Comment by asomers** [comment]
Ok.  BTW, it looks like bors can handle check-suites.  Could libc switch from Homu to Bors?  https://github.com/bors-ng/bors-ng/issues/421

**Comment by alexcrichton** [comment]
Perhaps! That's very much beyond the scope of this issue though!

**Pull request merged**
