### PR TITLE
Block nightlies on clippy

### PR DESCRIPTION
**Pull request by oli-obk**
cc @nrc @kennytm

### CODE REVIEW

**Comment by kennytm** [comment]
My preference is to modify `rustup` to refuse upgrade when rls/rustfmt/clippy is missing and user has installed it, rather than adding more roadblocks to nightlies.

**Comment by oli-obk** [comment]
I have no preference, I'm just implementing @nrc's suggestion:

> My plan is that I would like to get Clippy on dist and blocking nightlies at the end of this week. I need to get an 'ok' from the core team, but I think the time is right

And implementing the `rustup` no-upgrade feature probably will not be ready on Friday ;)

**Comment by kennytm** [comment]
> And implementing the `rustup` no-upgrade feature probably will not be ready on Friday ;)

Extending rust-lang-nursery/rustup.rs#1298 to cover all installed components shouldn't be too hard.

**Comment by pietroalbini** [comment]
> Extending rust-lang-nursery/rustup.rs#1298 to cover all installed components shouldn't be too hard.

That will conflict with https://github.com/rust-lang-nursery/rustup.rs/pull/1419.

**Comment by kennytm** [comment]
> If the component is just marked as `available = false` the old behavior (erroring out) is still used, since that might be caused by a CI failure (if I understand correctly).

So we could instead set missing RLS etc as `available = false` and everything should work fine?

**Comment by pietroalbini** [comment]
> So we could instead set missing RLS etc as available = false and everything should work fine?

With that patch yes, but rustup wasn't released since that PR was merged.

**Comment by kennytm** [comment]
🤔 Oh well.

**Comment by nrc** [comment]
We should do with Clippy the same thing we're doing with Rustfmt and RLS. If we want to make changes about how we keep nightlies running with broken tools, that should be a separate discussion.

**Comment by mati865** [comment]
> With that patch yes, but rustup wasn't released since that PR was merged.
New rustup version was just released.

**Pull request merged**
