### PR TITLE
Invalidate CloudFront distribution of docs

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates rust-central-station to invalidate CloudFront whenever a new
documentation build is published. Additionally the `publish_release` and
`update_dist_index` steps which uploads artifacts directly under `/dist` was
updated to not have a cache-control header of 0 because we'll invalidate it
below in CloudFront anyway.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ok I'm gonna merge this but if this has issues, please just let me know and we can look into them!

**Comment by alexcrichton** [comment]
Thanks for the info! I find that sort of surprising though that the *lack* of cache information means "cache indefinitely", but I guess there's not much we can do about that? FWIW rustup works with the "small index file" although it always has the same path, it just needs to be invalidated. We could try to set a "no cache" header for that and would that work for y'all?

**Comment by thibaultdelor** [comment]
FYI my problem is back, I can't update nightly because it's now cached.

Ideally yes you would put the no-cache header only on the index files and their sha256.

**Comment by thibaultdelor** [comment]
Second solution is to modify rustup to send the  "nocache" header as part of http request.

**Comment by alexcrichton** [comment]
@thibaultdelor this is only for the index, right? Not for the distributed or downloaded archives? In that case yeah I think a nocache header for rustup may be the best solution?

**Pull request merged**
