### PR TITLE
Host compiler documentation 

### PR DESCRIPTION
**Pull request by davidtwco**
This is the second half of rust-lang/rust#29893. The matching rust PR is rust-lang/rust#49193.

### CODE REVIEW

**Comment by davidtwco** [comment]
I've marked this as WIP as it hasn't been tested yet, until the matching Rust PR is merged and that produces tarballs, I'm not sure if it can.

**Comment by alexcrichton** [comment]
This tentatively looks good, thanks! I'll take a closer look at rust-lang/rust#49193 now

**Comment by davidtwco** [comment]
Renamed this to remove the `WIP` since rust-lang/rust#49193 has landed and this can now be properly tested.

**Comment by alexcrichton** [comment]
Ok great! One thing I actually realized though is that we'll want to gracefully handle the lack of a rustc-docs tarball as not all the stable/beta/nightly channels are currently producing one?

**Comment by davidtwco** [comment]
@alexcrichton I've pushed a commit that adds a check for this.

**Comment by Michael-F-Bryan** [comment]
@davidtwco, does this mean we'll have a place to view the API docs for rustc internals once this PR lands? At the moment I'm using a [rustc-internal-docs] "script" to run `./x.py doc` every night and upload the crate docs to GitHub Pages, but that's a pretty hacky solution and it looks like changes in `x.py` have broken it again (it no longer creates docs for `librustc_driver` and other internals).

@nikomatsakis, @mark-i-m, once this PR merges I believe `rustc-guide` should be able to link to the actual docs for various compiler internals (@davidtwco, feel free to correct me on this). It'd be much more useful to link to the rustdoc for structs/functions instead of the source code, and hopefully my `mdbook-linkcheck` will be able to detect broken links as things change.

[rustc-internal-docs]: https://github.com/Michael-F-Bryan/rustc-internal-docs

**Comment by davidtwco** [comment]
@Michael-F-Bryan If I'm not mistaken, they will be available at `doc.rust-lang.org/nightly-rustc/<crate_name>` (or something along those lines). I don't see any reason why you wouldn't be able to link to it.

**Comment by mark-i-m** [comment]
@Michael-F-Bryan could you open an issue on rustc-guide to change the links?

**Comment by nikomatsakis** [comment]
So excited for this. =)

**Comment by alexcrichton** [comment]
Thanks @davidtwco! This looks great to me now. We've got a release in a few days so I'm gonna hold off on merging this until that's done, but I'll merge and test after that.

**Comment by Manishearth** [comment]
(we've released!)

**Comment by Michael-F-Bryan** [comment]
Awesome work @davidtwco and @alexcrichton!

Will the new internal API docs be available when the next nightly is released?

**Comment by alexcrichton** [comment]
I've just now deployed this change to production, and yes hopefully after the next nightly we'll have shiny new docs!

**Comment by mark-i-m** [comment]
Where will they be hosted? `doc.rust-lang.org/nightly-rustc`?

**Comment by alexcrichton** [comment]
I believe it'll be doc.rust-lang.org/nightly/nightly-rustc

**Comment by mark-i-m** [comment]
I'm guessing #43 means we will get this for tomorrow's nightly instead?

**Comment by alexcrichton** [comment]
Documentation is [now live](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/)!

**Comment by mark-i-m** [comment]
Hmm... there appear to be some items missing. For example: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/interpret/index.html?search=mk_eval_cx which should show https://github.com/rust-lang/rust/blob/fb44b4c0eb1d344f84f7bb2c90f28e31a8a180be/src/librustc_mir/interpret/const_eval.rs#L40

Is this expected?

**Comment by Manishearth** [comment]
That's a private module

**Comment by mark-i-m** [comment]
Oh, are they not documented? Would it be possible to generate documentation for them? It would be nice to be able to link to them from the rustc-guide, and they are actually useful for devs...

**Comment by Manishearth** [comment]
Documenting private items for internals docs is being discussed [here](https://github.com/rust-lang/rust/issues/29893#issuecomment-378644068)

**Comment by mark-i-m** [comment]
Ah, great! Thanks @Manishearth :)

**Pull request merged**
