### PR TITLE
Give Centril (T-lang) rust-lang/rust try rights

### PR DESCRIPTION
**Pull request by Centril**
Pretty please? 😇

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I think as a team member you should have r+ rights, want to add yourself there instead?

**Comment by Centril** [comment]
@Mark-Simulacrum I don't feel comfortable having such rights just yet; but when I have more experience with compiler internals I'll ask for `r+` rights :)

**Comment by Centril** [comment]
@Mark-Simulacrum travis passed :)

**Comment by pietroalbini** [comment]
Ping for deploying @Mark-Simulacrum @alexcrichton @aidanhs

**Comment by Mark-Simulacrum** [comment]
This has been deployed, I believe.

**Pull request merged**
